--- # playbook demo of debug and register statements
- hosts: 127.0.0.1
  become: yes
  become_method: sudo
  connection: local
  gather_facts: no
  tasks:
  - name: Get pre-reqs
    apt:
      name: "{{ item }}"
      state: latest
    with_items:
      - git
      - g++
      - libgtk-3-dev
      - gtk-doc-tools
      - gnutls-bin
      - valac
      - libglib3.0-cil-dev
      - libgnutls28-dev
      - libgirepository1.0-dev
      - libxml2-utils
      - gperf
      - libpcre2-dev
      - libncurses-dev
      - libevent-dev
      - xcape
    register: result
  - name: get vte source
    git:
      repo: https://github.com/thestinger/vte-ng.git
      dest: /tmp/vte-ng
      update: yes
  - name: get termite source
    git:
      repo: https://github.com/thestinger/termite.git
      dest: /tmp/termite
      update: yes
      recursive: yes
  - name: configure vte source
    command: ./autogen.sh chdir=/tmp/vte-ng
  - name: build vte source
    command: make chdir=/tmp/vte-ng
  - name: install vte source
    command: make install chdir=/tmp/vte-ng
  - name: build termite source
    command: make chdir=/tmp/termite
  - name: install termite source
    command: make install chdir=/tmp/termite
  - name: get tmux source
    git:
      repo: https://github.com/tmux/tmux.git
      dest: /tmp/tmux
      update: yes
  - name: build configuration file for tmux
    command: sh autogen.sh chdir=/tmp/tmux
  - name: configure tmux
    command: ./configure chdir=/tmp/tmux
  - name: build tmux
    command: make chdir=/tmp/tmux
  - name: install tmux
    command: make install chdir=/tmp/tmux

  - debug: var=result
