name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --all-features --target x86_64-pc-windows-gnu
      - name: create zip file
        run: |
          zip -j github-tools-windows.zip ./target/x86_64-pc-windows-gnu/release/github-tools.exe
          
      - name: Upload windows binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.create_release.outputs.tag_name }}
          file: github-tools-windows.zip
          asset_name: github-tools-windows.zip
          overwrite: true
        
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --all-features --target x86_64-unknown-linux-gnu
      - name: create zip file
        run: |
          zip -j github-tools-linux.zip ./target/x86_64-unknown-linux-gnu/release/github-tools.exe

      - name: Upload linux binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.create_release.outputs.tag_name }}
          file: github-tools-linux.zip
          asset_name: github-tools-linux.zip
          overwrite: true
          
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --all-features --target x86_64-apple-darwin
      - name: create zip file
        run: |
          zip -j github-tools-macos.zip ./target/x86_64-apple-darwin/release/github-tools.exe
      
      - name: Upload macos binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.create_release.outputs.tag_name }}
          file: github-tools-macos.zip
          asset_name: github-tools-macos.zip
          overwrite: true
