---
name: Sample Workflow

on:
  push:
  workflow_dispatch:


# comment

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world" >> hello.txt
      - uses: actions/upload-artifact@v4
        with:
          name: hello
          path: hello.txt
  job2:
    name: Job 2
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: hello
      - run: cat hello.txt
  
